[package]
name = "solv-a-line"
version = "0.1.0"
authors = ["BryanDGuy"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"itertools" = "0.10.0"
"nalgebra" = "0.24.0"